### ISSUE TITLE
.element hover effect

### ISSUE THREAD

**Issue by cyouh95** [chrishardy80/ColmarAcademy#3]
To make the hover effect on your `.element` elements smoother, you could add the following:

```css
.element {
  padding: 12px;
  border: 4px solid transparent;
}
```

This adds a transparent `border` around the original element so that the hover effect does not cause the element to jump. Keeping the `padding` constant also helps.

https://github.com/chrishardy80/ColmarAcademy/blob/master/resources/css/style.css#L708-L718
